### ISSUE TITLE
ConfigParser error or cupp.py? idk 

### ISSUE THREAD

**Issue by M0ntanaT** [Mebus/cupp#1]
Traceback (most recent call last):
  File "/root/Desktop/cupp/cupp.py", line 50, in <module>
    years = config.get('years', 'years').split(',')
  File "/usr/lib/python2.7/ConfigParser.py", line 570, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'years'

**Comment by herrBez** [comment]
Could you please post your config file (cupp.cfg)? or try to re-download the program?

**Comment by alepacheco** [comment]
For anyone having the same problem, try lunching from the same folder with "./cupp.py" or "python cupp.py"

**Comment by Mebus** [comment]
Looks like a solution to the problem. Closing this issue.
