### ISSUE TITLE
Cupp error

### ISSUE THREAD

**Issue by KnownAsDon** [Mebus/cupp#21]
I have installed blackarch tools in vanilla archa and some extra tools such as cupp. I remember using it on kali and it used to work just fine but when i try to run the cupp.py file on arch now i get the following error:
`File "cupp.py", line 99
    print "[+] Saving dictionary to \033[1;31m"+filename+"\033[1;m, counting \033[1;31m"+str(lines)+" words.\033[1;m"
                                              ^
SyntaxError: invalid syntax
`

**Comment by JackRendor** [comment]
If you want to run `cupp.py`, you need to use python2: `python2 cupp.py`

Otherwise, if you want to use python3, you need to run the other script: `python3 cupp3.py`

**Comment by Mebus** [comment]
The Python 2 version has been removed from the repo. Please use

```
python3 cupp.py 
```

to run CUPP.
