### ISSUE TITLE
Download error for alectodb

### ISSUE THREAD

**Issue by vspitz** [Mebus/cupp#30]
The alectodb download fails.  I just pulled your most recent code today and ran into this issue.  Tried to find an answer to patch it myself but my python is lacking.  Just passing it along.

**command:**
python3 cupp3.py -a
**Result:**
Traceback (most recent call last):
  File "cupp3.py", line 723, in <module>
    main()
  File "cupp3.py", line 59, in main
    alectodb_download()
  File "cupp3.py", line 573, in alectodb_download
    local_file.write(web_file.read())
TypeError: write() argument must be str, not bytes

**Comment by Mebus** [comment]
This was fixed in bd62d47f5149a642985abb2f76eafc4ecca1f5a3 and I deleted cupp3.py because that was only an experimental version, that is currently unmaintained.
