### ISSUE TITLE
Can't run cupp

### ISSUE THREAD

**Issue by AbbliTLM** [Mebus/cupp#35]
Whenever I'm in the cupp folder, and I do 'python cupp.py' its prints this out: 
Traceback (most recent call last):
  File "cupp.py", line 40, in <module>
    import urllib.error
ImportError: No module named error

I reinstalled Kali Linux, reinstalled cupp and it's still not working.

**Comment by Mebus** [comment]
Please try "python3 cupp.py".

Mebus

**Comment by AbbliTLM** [comment]
it worked ty

**Comment by bobchris43** [comment]
Hi
Whenever I try "python cupp.py", I get this:
Traceback (most recent call last):
File "cupp.py", line 37, in <module>
import gzip
File "/usr/local/lib/python3.3/gzip.py", line 9, in <module>
import zlib
ImportError: No module named 'zlib'

**Comment by alberto64674yt** [comment]
lol y just type that in default directory root@kali# /root/.fsociety/tools/cupp/cupp.py that cause y use fsociety to get more tools and using that let me work cupp but if y open using fsociety get that XD:

Traceback (most recent call last):
  File "/root/.fsociety/tools/cupp/cupp.py", line 40, in <module>
    import urllib.error
ImportError: No module named error
Completed, click return to go back

so if anyone have errors using cupp whit fsociety try this XD

**Comment by Mebus** [comment]
Are you presenting a problem or a solution?

**Comment by bishalkharel** [comment]
sir can we use it n termux on android and if yes how i trued to do but when ever i try to run with python2 it says like this:
raceback (most recent call last):
  File "cupp.py", line 34, in <module>
    import configparser
ImportError: No module named configparser
please help me sir

**Comment by trroot** [comment]
lanet hatayı düzeltirmisin ?!

**Comment by Mebus** [comment]
> sir can we use it n termux on android and if yes how i trued to do but when ever i try to run with python2 it says like this:
> raceback (most recent call last):
> File "cupp.py", line 34, in
> import configparser
> ImportError: No module named configparser
> please help me sir

This is a Python 3 application only, in words: THREE. It is not supposed to be run in Python 2.

Mebus

**Comment by Mebus** [comment]
> raceback (most recent call last):
> File "cupp.py", line 40, in
> import urllib.error
> ImportError: No module named error
> 
> lanet hatayı düzeltirmisin ?!

You need to have the Python 3 urllib module.

**Comment by haides27** [comment]
> Please try "python3 cupp.py".
> 
> Mebus

it worked for me too thank you

**Comment by sadekb31** [comment]
> lol y just type that in default directory root@kali# /root/.fsociety/tools/cupp/cupp.py that cause y use fsociety to get more tools and using that let me work cupp but if y open using fsociety get that XD:
> 
> Traceback (most recent call last):
> File "/root/.fsociety/tools/cupp/cupp.py", line 40, in
> import urllib.error
> ImportError: No module named error
> Completed, click return to go back
> 
> so if anyone have errors using cupp whit fsociety try this XD

Hi you can fix this by changing the fsociety script:
- fsociety# cd /root/.fsociety/
- nano fsociety.py
- go to class cupp and change this line: ```
**def run(self):
        os.system("python %s/cupp.py -i" % self.installDir)**
```
to : ```
**def run(self):
        os.system("python3 %s/cupp.py -i" % self.installDir)**

:) 
```

**Comment by thisisnaimur** [comment]
cupp.py", line 34, in <module> import configparser ImportError: No module named configparser

**Comment by Yash6664** [comment]
getting this error, I can't solved, I trying almost 1 week on this.

Traceback (most recent call last):
  File "/root/cupp/cupp/cupp.py", line 1095, in <module>
    main()
  File "/root/cupp/cupp/cupp.py", line 1028, in main
    read_config(os.path.join(os.path.dirname(os.path.realpath(__file__)), "cupp.cfg"))
  File "/root/cupp/cupp/cupp.py", line 62, in read_config
    config.read(filename)
  File "/usr/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/usr/lib/python3.11/configparser.py", line 1112, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/root/cupp/cupp/cupp.cfg' [line 25]: option 's' in section 'leet' already exists
