### ISSUE TITLE
download databases

### ISSUE THREAD

**Issue by Nickpete** [Mebus/cupp#4]
Hi, thank you very much for solving the ftp server issue so fast,
I really apreciate.
Now, I managed to download some, but most give me the output below.
As far as I understand, it means the files are not available for download doesn't it?

[+] downloading dico.Z...
Traceback (most recent call last):
  File "cupp.py", line 1066, in <module>
    ftp.retrbinary('RETR ' + 'dico.Z', handleDownload)
  File "/usr/lib/python2.7/ftplib.py", line 406, in retrbinary
    conn = self.transfercmd(cmd, rest)
  File "/usr/lib/python2.7/ftplib.py", line 368, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python2.7/ftplib.py", line 331, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/lib/python2.7/ftplib.py", line 244, in sendcmd
    return self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 219, in getresp
    raise error_perm, resp
ftplib.error_perm: 550 Can't open dico.Z: No such file or directory

**Comment by ahmediraq** [comment]
Good

**Comment by herrBez** [comment]
Hi, 
I had the same issue and I resolved under Kali Linux by installing the package ftplib-dev.
Bye

**Comment by herrBez** [comment]
Hi, 
I have the same problem with the following dictionaries:
5, 6, 8, 9, 10, 12, 14, 15, 16, 18, 19, 20, 22, 25, 26, 27, 28, 30, 31
33, 35, 37

**Comment by Mebus** [comment]
I don't have enough time to fix this now. 

Do you have a fix for this?

**Comment by herrBez** [comment]
Not now, I'll try to find a solution. Thank you for the tool and the reply.

**Comment by herrBez** [comment]
Ok. I found the solution: 
ftp.funet.fi has changed the extension of all the .Z files to .gz.

**Comment by Mebus** [comment]
The last merge request should have fixed the issue now. Please test :-)
