### ISSUE TITLE
python cupp.py not working

### ISSUE THREAD

**Issue by bobchris43** [Mebus/cupp#40]
Hi
Whenever I try "python cupp.py", I get this:
Traceback (most recent call last):
File "cupp.py", line 37, in <module>
import gzip
File "/usr/local/lib/python3.3/gzip.py", line 9, in <module>
import zlib
ImportError: No module named 'zlib'

**Comment by setiyoajii** [comment]
Same😕

**Comment by Euzebius** [comment]
hum well ... "pip install zlib" should fix the thing ...

**Comment by Mebus** [comment]
Did that fix the issue?

**Comment by Assadi32** [comment]
Could not find a version that satisfies the requirement zlib (from versions: )
No matching distribution found for zlib

thts the error i got

**Comment by pumacutepa** [comment]
Need user password

**Comment by Paul7889** [comment]
Make sure to have python3 installed and type "python3 cupp.py".

**Comment by salikhThio** [comment]
> Assurez-vous que python3 est installé et tapez "python3 cupp.py".

ça marche. Good

**Comment by Mebus** [comment]
Closed, because obviously python3 was missing.

**Comment by saeedahm** [comment]
why cupp tool cant support , and - or __.__  
i det in config file but its not working i guess am i right or not?

**Comment by agustdaegu** [comment]
if that command doesn't work try "python cupp.py - i".
