### ISSUE TITLE
cupp error

### ISSUE THREAD

**Issue by bossrebal** [Mebus/cupp#45]

**Comment by bossrebal** [comment]
when i am run the cupp 
it show the erro
Traceback (most recent call last):
  File "cupp.py", line 42, in <module>
    import gzip
  File "/usr/local/lib/python3.7/gzip.py", line 9, in <module>
    import zlib
ModuleNotFoundError: No module named 'zlib'

**Comment by bishalkharel** [comment]
when ever i try to input it says like this 
raceback (most recent call last):
  File "cupp.py", line 34, in <module>
    import configparser
ImportError: No module named configparser

**Comment by bossrebal** [comment]
Any one give me a solution

**Comment by Mebus** [comment]
Are you using Python 2 or Python 3?

If you are using Python 3 then please try:

```
python3 -m pip install configparser
python3 -m pip install gzip
```

Note: It seems that there are currently some SSL problems with the python.org Repo :-O

Mebus

**Comment by bishalkharel** [comment]
i fixed the problem bro but thanks for replying
