### ISSUE TITLE
Make sure to have python3 installed and type "python3 cupp.py".

### ISSUE THREAD

**Issue by kamil638** [Mebus/cupp#65]
Make sure to have python3 installed and type "python3 cupp.py".

_Originally posted by @ghost in https://github.com/Mebus/cupp/issues/40#issuecomment-509407489_

**Comment by Mebus** [comment]
Why have you opened this issue?

Mebus

**Comment by shruuuu01** [comment]
I can't use these 
Change the password file name as pass.txt

mv oldname newname
mv filename.txt pass.txt
Open the file content

cat pass.txt
instacrack.py tool used for brute force attack
