### ISSUE TITLE
git clone https://github.com/Mebus/cupp.git

### ISSUE THREAD

**Issue by Omid1377230** [Mebus/cupp#87]
chmod +x cup.py
./cup.py –i

**Comment by Omid1377230** [comment]
chmod +x cup.py

**Comment by Omid1377230** [comment]
chmod +x cup.py

**Comment by Omid1377230** [comment]
>

**Comment by Mebus** [comment]
Could you please describe what your problem is?

**Comment by Omid1377230** [comment]
> Could you please describe what your problem is?

git clone

**Comment by Mebus** [comment]
```
git clone https://github.com/Mebus/cupp
```

Dosn't work or what is your problem?

Mebus
